In [1]:
import pandas as pd
from tkinter import filedialog as fd

In [2]:
file_path = fd.askopenfilename(
    title='Selecione o arquivo Excel com a lista de destinatarios',
    filetypes=[
        ('Arquivo Excel','.xls'),
        ('Arquivo Excel','.xlsx')]
    )

In [3]:
# ler arquivo Excel, precisa tres colunas
contatos_df = pd.read_excel(file_path, sheet_name='CLIENTES')

In [4]:
contatos_df

,CLIENTE,TELEFONE,MENSAGEM,RESULTADO,Unnamed: 4
0,Pablo,55(71) 9101-3035,Testing Message for Pablo,NaN,NaN
1,Pedro with valid message,55(71) 9101-3035,Testing Message for Pedro with valid message,NÃO recebeu a mensagem,NaN
2,Pedro Empty Message,555-5555,NaN,NaN,NaN
3,Pedro Wrong Number,555-5555,Testing Message for Pedro Wrong Number,NaN,Garbage
4,José valid message,55(71) 9101-3035,Testing Message for José valid message,NaN,NaN
5,José wrong number,555-5555,Testing Message for José wrong number,NaN,NaN
6,José Empty message,555-5555,NaN,NÃO recebeu a mensagem,NaN
7,Maria empty message,555-5555,NaN,NaN,NaN
8,Maria with message,555-5555,Testing Message for Maria with message,NÃO recebeu a mensagem,NaN
9,Maria Wrong number,NaN,Empty number,NÃO recebeu a mensagem,NaN
10,João message,55(71) 9101-3035,Testing Message for João message,NaN,NaN
11,Jõao wrong number,NaN,Empty number,NaN,NaN
12,Jõao long message,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
13,Fulano,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
14,Beltrano,555-5555,Testing Message for Beltrano,NaN,NaN
15,Sultano,555-5555,Testing Message for Sultano,NaN,NaN
16,Sicrano,55(71) 9101-3035,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN

In [5]:
contatos_df = contatos_df[~contatos_df['MENSAGEM'].isnull()]

In [6]:
contatos_df

,CLIENTE,TELEFONE,MENSAGEM,RESULTADO,Unnamed: 4
0,Pablo,55(71) 9101-3035,Testing Message for Pablo,NaN,NaN
1,Pedro with valid message,55(71) 9101-3035,Testing Message for Pedro with valid message,NÃO recebeu a mensagem,NaN
3,Pedro Wrong Number,555-5555,Testing Message for Pedro Wrong Number,NaN,Garbage
4,José valid message,55(71) 9101-3035,Testing Message for José valid message,NaN,NaN
5,José wrong number,555-5555,Testing Message for José wrong number,NaN,NaN
8,Maria with message,555-5555,Testing Message for Maria with message,NÃO recebeu a mensagem,NaN
9,Maria Wrong number,NaN,Empty number,NÃO recebeu a mensagem,NaN
10,João message,55(71) 9101-3035,Testing Message for João message,NaN,NaN
11,Jõao wrong number,NaN,Empty number,NaN,NaN
12,Jõao long message,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
13,Fulano,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
14,Beltrano,555-5555,Testing Message for Beltrano,NaN,NaN
15,Sultano,555-5555,Testing Message for Sultano,NaN,NaN
16,Sicrano,55(71) 9101-3035,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN

In [7]:
contatos_df = contatos_df[~contatos_df['TELEFONE'].isnull()]

In [8]:
contatos_df

,CLIENTE,TELEFONE,MENSAGEM,RESULTADO,Unnamed: 4
0,Pablo,55(71) 9101-3035,Testing Message for Pablo,NaN,NaN
1,Pedro with valid message,55(71) 9101-3035,Testing Message for Pedro with valid message,NÃO recebeu a mensagem,NaN
3,Pedro Wrong Number,555-5555,Testing Message for Pedro Wrong Number,NaN,Garbage
4,José valid message,55(71) 9101-3035,Testing Message for José valid message,NaN,NaN
5,José wrong number,555-5555,Testing Message for José wrong number,NaN,NaN
8,Maria with message,555-5555,Testing Message for Maria with message,NÃO recebeu a mensagem,NaN
10,João message,55(71) 9101-3035,Testing Message for João message,NaN,NaN
12,Jõao long message,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
13,Fulano,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
14,Beltrano,555-5555,Testing Message for Beltrano,NaN,NaN
15,Sultano,555-5555,Testing Message for Sultano,NaN,NaN
16,Sicrano,55(71) 9101-3035,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN

In [9]:
contatos_df.reset_index(inplace=True)

In [10]:
contatos_df

,index,CLIENTE,TELEFONE,MENSAGEM,RESULTADO,Unnamed: 4
0,0,Pablo,55(71) 9101-3035,Testing Message for Pablo,NaN,NaN
1,1,Pedro with valid message,55(71) 9101-3035,Testing Message for Pedro with valid message,NÃO recebeu a mensagem,NaN
2,3,Pedro Wrong Number,555-5555,Testing Message for Pedro Wrong Number,NaN,Garbage
3,4,José valid message,55(71) 9101-3035,Testing Message for José valid message,NaN,NaN
4,5,José wrong number,555-5555,Testing Message for José wrong number,NaN,NaN
5,8,Maria with message,555-5555,Testing Message for Maria with message,NÃO recebeu a mensagem,NaN
6,10,João message,55(71) 9101-3035,Testing Message for João message,NaN,NaN
7,12,Jõao long message,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
8,13,Fulano,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN
9,14,Beltrano,555-5555,Testing Message for Beltrano,NaN,NaN
10,15,Sultano,555-5555,Testing Message for Sultano,NaN,NaN
11,16,Sicrano,55(71) 9101-3035,A very long text message with a link here for ...,NÃO recebeu a mensagem,NaN

In [11]:
contatos_df = contatos_df[['CLIENTE','TELEFONE','MENSAGEM','RESULTADO']].copy()
# contatos_df.drop(['index'],axis=1,inplace=True)

In [24]:
contatos_df

,CLIENTE,TELEFONE,MENSAGEM,RESULTADO
0,Pablo,55(71) 9101-3035,Testing Message for Pablo,NaN
1,Pedro with valid message,55(71) 9101-3035,Testing Message for Pedro with valid message,NÃO recebeu a mensagem
2,Pedro Wrong Number,555-5555,Testing Message for Pedro Wrong Number,NaN
3,José valid message,55(71) 9101-3035,Testing Message for José valid message,NaN
4,José wrong number,555-5555,Testing Message for José wrong number,NaN
5,Maria with message,555-5555,Testing Message for Maria with message,NÃO recebeu a mensagem
6,João message,55(71) 9101-3035,Testing Message for João message,NaN
7,Jõao long message,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem
8,Fulano,555-5555,A very long text message with a link here for ...,NÃO recebeu a mensagem
9,Beltrano,555-5555,Testing Message for Beltrano,NaN
10,Sultano,555-5555,Testing Message for Sultano,NaN
11,Sicrano,55(71) 9101-3035,A very long text message with a link here for ...,NÃO recebeu a mensagem

In [13]:
len(contatos_df[contatos_df['RESULTADO'] == 'NÃO recebeu a mensagem'])

5

In [14]:
len(contatos_df)

12

In [15]:
fails = len(contatos_df[contatos_df['RESULTADO'] == 'NÃO recebeu a mensagem'])/len(contatos_df)

In [16]:
texto = '''Contanto numero de falhas\nFalhas: {:.2%}'''.format(fails)

In [17]:
print(texto)

Contanto numero de falhas
Falhas: 41.67%

In [28]:
len(contatos_df[contatos_df['RESULTADO'].str.contains('Recebeu') == True])

0

: